### ISSUE TITLE
Not work on the Sublime text 3.0

### ISSUE THREAD

**Issue by yaosing** [victorporof/Sublime-HTMLPrettify#516]
When I click prettify code it show the error message: 'str' object has no attribute 'get'. How to fix it?

**Comment by victorporof** [comment]
This is something I've never seen before! Care to post sublime's console output and some minimal steps to reproduce?

**Comment by ttscoff** [comment]
I'm getting this as well, fresh install of the plugin. The only thing that shows up in the console is:

     'str' object has no attribute 'get'

Running it on a mostly empty html5 skeleton. /usr/local/bin/tidy is `HTML Tidy for Apple macOS version 5.6.0`.
